---
title: "loc_pathways_2026-04-27"
output: pdf_document
---

```{r setup, include = FALSE}
library("papaja")
library("DescTools")
library("tidyr")
library("dplyr")
library("summarytools")
library("ggplot2")
library("jtools")
library("flextable")
library("psych")

#Set working directory to loc_pathways/Reports
dat <- read.csv("../Data/loc_pathways_data_2026-03-31.csv")
```

```{r recoding}
dat <- dat %>%
  mutate(gender = recode(gender,
    "0" = "female",
    "1" = "male"))

dat <- dat %>%
  mutate(usborn = recode(usborn,
    "0" = "born in the US",
    "1" = "not born in the US"))

nrow(dat)
meanage <- mean(dat$age, na.rm = TRUE)
sdage <- sd(dat$age, na.rm = TRUE)
rangeage <- range(dat$age, na.rm = TRUE)
minage <- min(dat$age, na.rm = TRUE)
maxage <- min(dat$age, na.rm = TRUE)
modeeid <- Mode(dat$eid_ethnicity_coded, na.rm = TRUE)
modegender <- Mode(dat$gender, na.rm = TRUE)
modeusborn <- Mode(dat$usborn, na.rm = TRUE)
```

```{r descriptive table, echo = FALSE}
#Gender
gender_n <- ""
gender_p <- ""
male_n <- sum(dat$gender == "male", na.rm = TRUE)
male_p <- round((male_n/nrow(dat) * 100), digits = 2)
female_n <- sum(dat$gender == "female", na.rm = TRUE)
female_p <- round((female_n/nrow(dat) * 100), digits = 2)
no_report_n <- sum(is.na(dat$gender))
no_report_p <- round((no_report_n/nrow(dat) * 100), digits = 2)

#Race
race_n <- ""
race_p <- ""
asian_n <- sum(dat$eid_ethnicity_coded == "Asian/Pacific Islander")
asian_p <- round((asian_n/nrow(dat) * 100), digits = 2)
black_n <- sum(dat$eid_ethnicity_coded == "Black/African American")
black_p <- round((black_n/nrow(dat) * 100), digits = 2)
latin_n <- sum(dat$eid_ethnicity_coded == "Hispanic/Latine")
latin_p <- round((latin_n/nrow(dat) * 100), digits = 2)
multi_n <- sum(dat$eid_ethnicity_coded == "Multiracial")
multi_p <- round((multi_n/nrow(dat) * 100), digits = 2)
native_n <- sum(dat$eid_ethnicity_coded == "Native American")
native_p <- round((native_n/nrow(dat) * 100), digits = 2)
white_n <- sum(dat$eid_ethnicity_coded == "White/European American")
white_p <- round((white_n/nrow(dat) * 100), digits = 2)
other_race_n <- sum(dat$eid_ethnicity_coded == "Other")
other_race_p <- round((other_race_n/nrow(dat) * 100), digits = 2)

#US-Born
row_us_born_n <- ""
row_us_born_p <- ""
us_born_n <- sum(dat$usborn == "born in the US")
us_born_p <- round((us_born_n/nrow(dat) * 100), digits = 2)
not_us_born_n <- sum(dat$usborn == "not born in the US")
not_us_born_p <- round((not_us_born_n/nrow(dat) * 100), digits = 2)

#Making demographic table
dem_table <- tribble(
    ~Characteristic, ~n, ~`%`,
    "Gender", gender_n, gender_p,
    "     Male", as.factor(male_n), as.factor(male_p),
    "     Female", as.factor(female_n), as.factor(female_p),
    "     Uncategorized", as.factor(no_report_n), as.factor(no_report_p),
    "Race", race_n, race_p,
    "     Asian/Pacific Islander", as.factor(asian_n), as.factor(asian_p),
    "     Black/African American", as.factor(black_n), as.factor(black_p),
    "     Hispanic/Latine", as.factor(latin_n), as.factor(latin_p),
    "     Multiracial", as.factor(multi_n), as.factor(multi_p),
    "     Native American", as.factor(native_n), as.factor(native_p),
    "     White/European American", as.factor(white_n), as.factor(white_p),
    "     Other", as.factor(other_race_n), as.factor(other_race_p),
    "Birthplace", row_us_born_n, row_us_born_p,
    "     Born in the US", as.factor(us_born_n), as.factor(us_born_p),
    "     Not Born in the US", as.factor(not_us_born_n), as.factor(not_us_born_p)
    )

table_1_caption <- "N = 92. Participants were 18.15 years old on average (SD = 1.07)"

apa_table(dem_table, 
          caption = "Sociodemographic Characteristics of Participants", 
          align = NULL, 
          digits = 2, 
          note = table_1_caption)
```

```{r data vis, include = FALSE}
#Making subsets per pathway
uncertain_dat <- dat %>% 
  filter(dat$pathway_final == "uncertain")

discovery_dat <- dat %>% 
  filter(dat$pathway_final == "discovery")

redirect_dat <- dat %>% 
  filter(dat$pathway_final == "redirect")

solidification_dat <- dat %>% 
  filter(dat$pathway_final == "solidification")

certain_dat <- dat %>% 
  filter(dat$pathway_final == "certain")

#Uncertain pathway: pivot, anova, plot
uncertain_dat_long <- pivot_longer(uncertain_dat,
                                 34:37,
                                 names_to = "wave",
                                 values_to = "loc")

uncertain_aov <- aov(loc ~ wave, data = uncertain_dat_long)
uncertain_sum <- summary(uncertain_aov)
uncertain_f <- uncertain_sum[[1]][["F value"]][1]
uncertain_p <- uncertain_sum[[1]][["Pr(>F)"]][1]
uncertain_df <- uncertain_sum[[1]][["Df"]][1]
uncertain_df2 <- uncertain_sum[[1]][["Df"]][2]
TukeyHSD(uncertain_aov)

uncertain_plot <- ggplot(uncertain_dat_long, aes(wave, loc, fill = wave)) +
  geom_boxplot() +
  ggtitle("Uncertain Pathway: Changes in Locus of Control") +
  xlab("Wave") +
  ylab("Locus of Control") +
  scale_x_discrete(labels = c("Wave 1", "Wave 2", "Wave 3", "Wave 4")) +
  jtools::theme_apa() +
  theme(legend.position = "none")

#Discovery pathway: pivot, aov, plot
discovery_dat_long <- pivot_longer(discovery_dat,
                                 34:37,
                                 names_to = "wave",
                                 values_to = "loc")

discovery_aov <- aov(loc ~ wave, data = discovery_dat_long)
discovery_sum <- summary(discovery_aov)
discovery_f <- discovery_sum[[1]][["F value"]][1]
discovery_p <- discovery_sum[[1]][["Pr(>F)"]][1]
discovery_df <- discovery_sum[[1]][["Df"]][1]
discovery_df2 <- discovery_sum[[1]][["Df"]][2]
TukeyHSD(discovery_aov)

discovery_plot <- ggplot(discovery_dat_long, aes(wave, loc, fill = wave)) +
  geom_boxplot() +
  ggtitle("Discovery Pathway: Changes in Locus of Control") +
  xlab("Wave") +
  ylab("Locus of Control") +
  scale_x_discrete(labels = c("Wave 1", "Wave 2", "Wave 3", "Wave 4")) +
  jtools::theme_apa() +
  theme(legend.position = "none")

discovery_dat_long <- pivot_longer(discovery_dat,
                                 34:37,
                                 names_to = "wave",
                                 values_to = "loc")

#Redirect pathway: pivot, aov, plot
redirect_dat_long <- pivot_longer(redirect_dat,
                                 34:37,
                                 names_to = "wave",
                                 values_to = "loc")

redirect_aov <- aov(loc ~ wave, data = redirect_dat_long)
redirect_sum <- summary(redirect_aov)
redirect_f <- redirect_sum[[1]][["F value"]][1]
redirect_p <- redirect_sum[[1]][["Pr(>F)"]][1]
redirect_df <- redirect_sum[[1]][["Df"]][1]
redirect_df2 <- redirect_sum[[1]][["Df"]][2]
TukeyHSD(redirect_aov)

redirect_plot <- ggplot(redirect_dat_long, aes(wave, loc, fill = wave)) +
  geom_boxplot() +
  ggtitle("Redirect Pathway: Changes in Locus of Control") +
  xlab("Wave") +
  ylab("Locus of Control") +
  scale_x_discrete(labels = c("Wave 1", "Wave 2", "Wave 3", "Wave 4")) +
  jtools::theme_apa() +
  theme(legend.position = "none")

#Solidification pathway: pivot, aov, plot
solidification_dat_long <- pivot_longer(solidification_dat,
                                 34:37,
                                 names_to = "wave",
                                 values_to = "loc")

solidification_aov <- aov(loc ~ wave, data = solidification_dat_long)
solidification_sum <- summary(solidification_aov)
solidification_f <- solidification_sum[[1]][["F value"]][1]
solidification_p <- solidification_sum[[1]][["Pr(>F)"]][1]
solidification_df <- solidification_sum[[1]][["Df"]][1]
solidification_df2 <- solidification_sum[[1]][["Df"]][2]
TukeyHSD(solidification_aov)

solidification_plot <- ggplot(solidification_dat_long, aes(wave, loc, fill = wave)) +
  geom_boxplot() +
  ggtitle("Solidification Pathway: Changes in Locus of Control") +
  xlab("Wave") +
  ylab("Locus of Control") +
  scale_x_discrete(labels = c("Wave 1", "Wave 2", "Wave 3", "Wave 4")) +
  jtools::theme_apa() +
  theme(legend.position = "none")

#Certain pathway: pivot, aov, plot
certain_dat_long <- pivot_longer(certain_dat,
                                 34:37,
                                 names_to = "wave",
                                 values_to = "loc")

certain_aov <- aov(loc ~ wave, data = certain_dat_long)
certain_sum <- summary(certain_aov)
certain_f <- certain_sum[[1]][["F value"]][1]
certain_p <- certain_sum[[1]][["Pr(>F)"]][1]
certain_df <- certain_sum[[1]][["Df"]][1]
certain_df2 <- certain_sum[[1]][["Df"]][2]
TukeyHSD(certain_aov)

certain_plot <- ggplot(certain_dat_long, aes(wave, loc, fill = wave)) +
  geom_boxplot() +
  ggtitle("Certain Pathway: Changes in Locus of Control") +
  xlab("Wave") +
  ylab("Locus of Control") +
  scale_x_discrete(labels = c("Wave 1", "Wave 2", "Wave 3", "Wave 4")) +
  jtools::theme_apa() +
  theme(legend.position = "none")

#I will try to join all 5 dataframes and facet_wrap to make one chart with all 5 boxplots
dat_long <- rbind(uncertain_dat_long, discovery_dat_long, redirect_dat_long, solidification_dat_long, certain_dat_long)

dat_plot <- ggplot(dat_long, aes(pathway_final, loc, fill = wave)) +
  geom_boxplot() +
  xlab("Major Pathway") +
  ylab("Locus of Control") +
  jtools::theme_apa() +
  theme(legend.position = "right") +
  scale_fill_discrete(
        labels = c("t1_loc" = "Time 1", "t2_loc" = "Time 2", "t3_loc" = "Time 3", "t4_loc" = "Time 4")
      ) +
  scale_x_discrete(labels = c("Certain", "Discovery", "Redirect", "Solidification", "Uncertain")) +
  labs(fill = "Time")

```

```{r paired samples t-tests}
#Uncertain
uncertain_t_test <- uncertain_dat %>% 
  select(t1_loc, t4_loc)

mean(uncertain_t_test$t1_loc)
sd(uncertain_t_test$t1_loc)

mean(uncertain_t_test$t4_loc)
sd(uncertain_t_test$t4_loc)
  
uncertain_results <- t.test(uncertain_t_test$t1_loc, uncertain_t_test$t4_loc, paired = TRUE)
print(uncertain_results)

#Discovery
discovery_t_test <- discovery_dat %>% 
  select(t1_loc, t4_loc)
  
mean(discovery_t_test$t1_loc)
sd(discovery_t_test$t1_loc)

mean(discovery_t_test$t4_loc)
sd(discovery_t_test$t4_loc)

discovery_results <- t.test(discovery_t_test$t1_loc, discovery_t_test$t4_loc, paired = TRUE)
print(discovery_results)

#Redirect
redirect_t_test <- redirect_dat %>% 
  select(t1_loc, t4_loc)

mean(redirect_t_test$t1_loc)
sd(redirect_t_test$t1_loc)

mean(redirect_t_test$t4_loc)
sd(redirect_t_test$t4_loc)
  
redirect_results <- t.test(redirect_t_test$t1_loc, redirect_t_test$t4_loc, paired = TRUE)
print(redirect_results)

#Solidification
solidification_t_test <- solidification_dat %>% 
  select(t1_loc, t4_loc)
  
mean(solidification_t_test$t1_loc)
sd(solidification_t_test$t1_loc)

mean(solidification_t_test$t4_loc)
sd(solidification_t_test$t4_loc)

solidification_results <- t.test(solidification_t_test$t1_loc, solidification_t_test$t4_loc, paired = TRUE)
print(solidification_results)

#Certain
certain_t_test <- certain_dat %>% 
  select(t1_loc, t4_loc)
  
mean(certain_t_test$t1_loc)
sd(certain_t_test$t1_loc)

mean(certain_t_test$t4_loc)
sd(certain_t_test$t4_loc)

certain_results <- t.test(certain_t_test$t1_loc, certain_t_test$t4_loc, paired = TRUE)
print(certain_results)
```

```{r line graph}
line_dat <- tribble(
  ~pathway,    ~wave,  ~loc,
  "Uncertain", 1, mean(uncertain_dat$t1_loc),
  "Uncertain", 2, mean(uncertain_dat$t2_loc),
  "Uncertain", 3, mean(uncertain_dat$t3_loc),
  "Uncertain", 4, mean(uncertain_dat$t4_loc),
  "Discovery", 1, mean(discovery_dat$t1_loc),
  "Discovery", 2, mean(discovery_dat$t2_loc),
  "Discovery", 3, mean(discovery_dat$t3_loc),
  "Discovery", 4, mean(discovery_dat$t4_loc),
  "Redirect", 1, mean(redirect_dat$t1_loc),
  "Redirect", 2, mean(redirect_dat$t2_loc),
  "Redirect", 3, mean(redirect_dat$t3_loc),
  "Redirect", 4, mean(redirect_dat$t4_loc),
  "Solidification", 1, mean(solidification_dat$t1_loc),
  "Solidification", 2, mean(solidification_dat$t2_loc),
  "Solidification", 3, mean(solidification_dat$t3_loc),
  "Solidification", 4, mean(solidification_dat$t4_loc),
  "Certain", 1, mean(certain_dat$t1_loc),
  "Certain", 2, mean(certain_dat$t2_loc),
  "Certain", 3, mean(certain_dat$t3_loc),
  "Certain", 4, mean(certain_dat$t4_loc)
)

levels(as.factor(line_dat$pathway))

line_plot <- ggplot(line_dat, aes(x = wave, y = loc, color = pathway)) + 
  geom_line() +
  geom_point() +
  xlab("Time") +
  ylab("Locus of Control") +
  jtools::theme_apa() +
  theme(legend.position = "right") +
  scale_fill_discrete(
        labels = c("1" = "Wave 1", "2" = "Wave 2", "3" = "Wave 3", "4" = "Wave 4")
      ) +
  scale_y_continuous(limits = c(3, 4.5))
```

```{r reliability estimate}
colnames(dat)
t1 <- alpha(dat[, 14:18])
print(t1) #0.57

t2 <- alpha(dat[, 19:23])
print(t2) #0.62

t3 <- alpha(dat[, 24:28])
print(t3) #0.72

t4 <- alpha(dat[, 29:33])
print(t4) #0.76
```