% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
  english,
  man,floatsintext]{apa6}
\usepackage{xcolor}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
\ifLuaTeX
\usepackage[bidi=basic]{babel}
\else
\usepackage[bidi=default]{babel}
\fi
% get rid of language-specific shorthands (see #6817):
\let\LanguageShortHands\languageshorthands
\def\languageshorthands#1{}
\ifLuaTeX
  \usepackage[english]{selnolig} % disable illegal ligatures
\fi
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
% Manuscript styling
\usepackage{upgreek}
\captionsetup{font=singlespacing,justification=justified}

% Table formatting
\usepackage{longtable}
\usepackage{lscape}
% \usepackage[counterclockwise]{rotating}   % Landscape page setup for large tables
\usepackage{multirow}		% Table styling
\usepackage{tabularx}		% Control Column width
\usepackage[flushleft]{threeparttable}	% Allows for three part tables with a specified notes section
\usepackage{threeparttablex}            % Lets threeparttable work with longtable

% Create new environments so endfloat can handle them
% \newenvironment{ltable}
%   {\begin{landscape}\centering\begin{threeparttable}}
%   {\end{threeparttable}\end{landscape}}
\newenvironment{lltable}{\begin{landscape}\centering\begin{ThreePartTable}}{\end{ThreePartTable}\end{landscape}}

% Enables adjusting longtable caption width to table width
% Solution found at http://golatex.de/longtable-mit-caption-so-breit-wie-die-tabelle-t15767.html
\makeatletter
\newcommand\LastLTentrywidth{1em}
\newlength\longtablewidth
\setlength{\longtablewidth}{1in}
\newcommand{\getlongtablewidth}{\begingroup \ifcsname LT@\roman{LT@tables}\endcsname \global\longtablewidth=0pt \renewcommand{\LT@entry}[2]{\global\advance\longtablewidth by ##2\relax\gdef\LastLTentrywidth{##2}}\@nameuse{LT@\roman{LT@tables}} \fi \endgroup}

% \setlength{\parindent}{0.5in}
% \setlength{\parskip}{0pt plus 0pt minus 0pt}

% Overwrite redefinition of paragraph and subparagraph by the default LaTeX template
% See https://github.com/crsh/papaja/issues/292
\makeatletter
\renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
  {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
  {-1em}%
  {\normalfont\normalsize\bfseries\itshape\typesectitle}}

\renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{1em}%
  {0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
  {-\z@\relax}%
  {\normalfont\normalsize\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
\makeatother

\makeatletter
\usepackage{etoolbox}
\patchcmd{\maketitle}
  {\section{\normalfont\normalsize\abstractname}}
  {\section*{\normalfont\normalsize\abstractname}}
  {}{\typeout{Failed to patch abstract.}}
\patchcmd{\maketitle}
  {\section{\protect\normalfont{\@title}}}
  {\section*{\protect\normalfont{\@title}}}
  {}{\typeout{Failed to patch title.}}
\makeatother

\usepackage{xpatch}
\makeatletter
\xapptocmd\appendix
  {\xapptocmd\section
    {\addcontentsline{toc}{section}{\appendixname\ifoneappendix\else~\theappendix\fi: #1}}
    {}{\InnerPatchFailed}%
  }
{}{\PatchFailed}
\makeatother
\keywords{College major choice, undergraduate students, locus of control, self-authorship\newline\indent Word count: 542}
\usepackage{csquotes}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Changes in Locus of Control Orientation Across College Major Pathways},
  pdfauthor={Varsha Venkatesh1 \& Moin Syed1},
  pdflang={en-EN},
  pdfkeywords={College major choice, undergraduate students, locus of control, self-authorship},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Changes in Locus of Control Orientation Across College Major Pathways}
\author{Varsha Venkatesh\textsuperscript{1} \& Moin Syed\textsuperscript{1}}
\date{}


\shorttitle{Locus of Control and Major Pathways}

\authornote{

The authors made the following contributions. Varsha Venkatesh: Conceptualization, Writing - Original Draft Preparation, Writing - Review \& Editing; Moin Syed: Writing - Review \& Editing, Supervision.

Correspondence concerning this article should be addressed to Varsha Venkatesh, 75 E River Pkwy, Minneapolis, MN 55455. E-mail: \href{mailto:venka288@umn.edu}{\nolinkurl{venka288@umn.edu}}

}

\affiliation{\vspace{0.5cm}\textsuperscript{1} University of Minnesota}

\abstract{%
Choosing a college major is among the most important and difficult decisions that a student makes in their career. The present study seeks to better understand how feelings of control and agency can impact this choice. In particular, we do so by examining how locus of control changes among undergraduate students over the course of the first two years of college and how these patterns vary across different major pathways. The current student expands upon past research in three major ways. Firstly, previous studies of college student major choice more broadly compare undecided and decided students as opposed to narrower paths toward college major choice. Secondly, most previous studies of major choice examine group differences at one timepoint, rather than longitudinally. Finally, while locus of control has been extensively studied, there is a dearth of research on how locus of control changes over time, particularly among undergraduate students. Based on past studies of locus of control and decision-making as well as Baxter Magolda's theory of self-authorship, we hypothesized that across the five major pathways measured in this study (uncertain, discovery, redirect, solidification, and certain), we would observe varied longitudinal patterns of locus of control.
}



\begin{document}
\maketitle

\begin{verbatim}
## [1] 92
\end{verbatim}

\begin{verbatim}
## [1] 18.15385
\end{verbatim}

\begin{verbatim}
## [1] 1.074172
\end{verbatim}

\begin{table}[tbp]

\begin{center}
\begin{threeparttable}

\caption{\label{tab:descriptive table}Sociodemographic Characteristics of Participants}

\begin{tabular}{lll}
\toprule
Characteristic & \multicolumn{1}{c}{n} & \multicolumn{1}{c}{\%}\\
\midrule
Gender &  & \\
\ \ \ \  Male & 69 & 75\\
\ \ \ \  Female & 22 & 23.91\\
\ \ \ \  Uncategorized & 1 & 1.09\\
Race &  & \\
\ \ \ \  Asian/Pacific Islander & 55 & 59.78\\
\ \ \ \  Black/African American & 17 & 18.48\\
\ \ \ \  Hispanic/Latine & 8 & 8.7\\
\ \ \ \  Multiracial & 2 & 2.17\\
\ \ \ \  Native American & 1 & 1.09\\
\ \ \ \  White/European American & 2 & 2.17\\
\ \ \ \  Other & 7 & 7.61\\
Birthplace &  & \\
\ \ \ \  Born in the US & 64 & 69.57\\
\ \ \ \  Not Born in the US & 28 & 30.43\\
\bottomrule
\addlinespace
\end{tabular}

\begin{tablenotes}[para]
\normalsize{\textit{Note.} N = 92. Participants were 18.15 years old on average (SD = 1.07)}
\end{tablenotes}

\end{threeparttable}
\end{center}

\end{table}


\end{document}
